### PR TITLE
feat:Added landing page

### PR DESCRIPTION
**Pull request by Hardiegogo**

### CODE REVIEW

**Comment by ashishnnnnn** [comment]
Code look fine..
The way of dividing the css style in components is awesome ..

**Comment by prathmeshjagtap** [comment]
Code is well written and easy to understand also well formated and divided nicely with components.

**Comment by spraveenofficial** [comment]
Well structured though. You can merge ✌️

**Comment by Hardiegogo** [comment]
> Code look fine.. The way of dividing the css style in components is awesome ..

Thank you!

**Comment by Hardiegogo** [comment]
> Code is well written and easy to understand also well formated and divided nicely with components.

Thank you! I will go ahead and merge it now.

**Comment by Hardiegogo** [comment]
> Well structured though. You can merge ✌️

Got it. Okay.

**Pull request merged**
