### PR TITLE
feat:Added text-utils and navbar

### PR DESCRIPTION
**Pull request by Hardiegogo**
Added text-utils:

- Headings
- paragraph text
- grey text and centered text

Added Navbar

### CODE REVIEW

**Review by AmishMishra11 — COMMENTED** [review]
looks good to merge

**Review by ArjunGTX — APPROVED** [review]
Everything looking good

**Comment by Hardiegogo** [comment]
> looks good to merge

Okay , Thank you Amish.

**Comment by Hardiegogo** [comment]
> Everything looking good

Thank you Arjun.

**Pull request merged**
